services:
  app:
    build: .
    ports:
      - "8020:8000"
    volumes:
      - .:/app
      - shared-data:/shared-data
    user: root
    environment:
      - UV_PROJECT_ENVIRONMENT=/opt/venv
    env_file:
      - .env
    working_dir: /app
    command: ["uv", "run", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

volumes:
  shared-data:
    external: true
    name: shared-data
